### ISSUE TITLE
wrong host for url helpers in feature specs

### ISSUE THREAD

**Issue by anujbiyani** [rspec/rspec-rails#1174]
In a bunch of my feature specs, when I call `*_url` helpers the host is `"www.example.com"` instead of what I've configured. I noticed that https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/example/feature_example_group.rb#L9 hardcodes the default host and there doesn't seem to be a way to change it.

If I monkey-patch the constant to what I want, then the `*_url` helpers give me the correct host.

Is there a reason why `FeatureExampleGroup::DEFAULT_HOST` isn't configurable?

**Comment by iainbeeston** [comment]
I'm experiencing this issue as well.

I'm testing a page using capybara. I have a form input that is pre populated with a url, and I have an expectation that the value of this input should match the one returned by a rail url helper (eg. expect(input.value).to eq(users_url)).

I've changed the default host used by capybara, and the default url opts rails. The value generated (by rails) for the input has the correct host. But unfortunately the value in my spec that I'm testing it against (eg. users_url) has the host set to www.example.com, instead of the one that rails is using.

Delving into the code (at runtime) for the feature example group, no matter what I do I can never get it to find the default_url_options that I've set in rails (should this be coming from routes.url_helpers? Or routes.mounted_url_helpers?). Interestingly, the code for mailer example group explicitly merges in 
    Rails.configuration.action_mailer.default_url_options (but feature example group does nothing similar).

Can we reopen this issue? I'd be glad to help track down the cause

**Comment by iainbeeston** [comment]
If, in my spec, I directly access the rails url helper (eg. Rails.application.routes.url_helpers.users_url) I get a url with the correct host (whereas if I just rely on the version in the feature example group it has the incorrect host)

**Comment by lime** [comment]
Note to others who encounter this: #1275 discusses the same problem, and is still open at the time of writing.
