### ISSUE TITLE
Allow the set the controller spec routes globally.

### ISSUE THREAD

**Issue by tvdeyen** [rspec/rspec-rails#1226]
For testing controllers in an rails engine one can set the engine routes inside the controller spec file:

https://www.relishapp.com/rspec/rspec-rails/v/3-1/docs/controller-specs/engine-routes-for-controllers

Great, but it is very tedious to set this in every single controller spec. Especially for large rails engines, like spree or alchemy.

It would be great if one could set the routes globally like this:

``` ruby
# spec_helper.rb
RSpec.configure do |config|
  config.before(:each) do
    # Load the routes for controller specs
    if example.metadata[:type] == :controller
      example.routes { Alchemy::Engine.routes }
    end
  end
end
```

**Comment by cupakromer** [comment]
@jfelchner can you specify what didn't work and the error you get? I just checked with Rails 4.2 and that line does work in a controller spec for me.

**Comment by jfelchner** [comment]
Sorry for the "it's broke" with no info.  I'm gonna try to dig into this later tonight.

Here's the exact error I'm getting:

> DEPRECATION WARNING: You are trying to generate the URL for a named route called "my_engine" but no such route was found. In the future, this will result in an `ActionController::UrlGenerationError` exception.

I have a fairly complex setup.  One thing in particular is that all of my controllers are inside of submodules.  So my spec setup looks like this:

```ruby
require 'spec_helper'

module    MyEngine
module    Api
module    V1
describe  MyController do
  routes { GoodScouter::Engine.routes }

  it 'knocks it out of the park' do
    # Spec
  end
end
end
end
```

If you have any ideas offhand I'd love to hear them, but I'm def gonna look at this later tonight.

**Comment by cupakromer** [comment]
@jfelchner what rspec version are you on? I'm testing with what's on `master`, but would like to try your version. Also, can you share your repo or the full spec which causes the warning?

Based on the error message it sounds like you're calling a named route, which isn't normally something you do in a controller spec. Is that caused by the controller code itself?

**Comment by jfelchner** [comment]
@cupakromer there are so many things busted in Rails 4.2 I'm working through them one by one. :smile: Lemme ping you back either later tonight or tomorrow.

**Comment by cupakromer** [comment]
@jfelchner please note that 4.2 support only begins with rspec-rails 3.1:heart: Let me know how things go.

**Comment by jfelchner** [comment]
@cupakromer I use a gem to copy all of my shared Rspec configurations from project to project and I'd completely forgotten that in there I was monkey-patching all of the controller action methods because of I'd run into this very problem a few months ago.

Changing my current code to a variation on your code above made it work perfectly. 

Thanks :smile: :heart:

https://github.com/thekompanee/rspectacular/commit/ff4167f1debf571b78bec1543e79a1a9e9868d76

**Comment by jfelchner** [comment]
@cupakromer so now that we can't use the other hack I was using, I've run into one more small problem.

I have some controller modules that I want to test in an isolated way.  Currently I have something like this:

```ruby
require 'spec_helper'

class MyTestController < ActionController::Base
  include MyModuleUnderTest

  # very small custom action behavior like:
  def index
    render text:   'Success',
           status: :success
  end
end

describe MyTestController do
  it 'has an index action that does stuff' do
    get :index

    # other stuff
  end
end
```

Which worked great until the changes we've been talking about.

Obviously I don't want this route in my engine.  And I'd prefer not drawing the route in this spec since it'll persist for all specs that follow it.

Any ideas?

**Comment by huoxito** [comment]
@jfelchner iirc `@routes` is defined on a per example basis so if you do something like [this](https://github.com/spree/spree/blob/e845f64cf118387063fd5df61c1a104a8ab31b60/api/spec/controllers/spree/api/base_controller_spec.rb#L127-129) it will only affect that particular context spec

**Comment by jfelchner** [comment]
@huoxito perfect! I didn't realize defining custom routes in a spec was that easy!

**Comment by jfelchner** [comment]
I think since we have a solution here this can be closed out yes?  It seems like there isn't much traction on it anyway.

**Comment by jfelchner** [comment]
@tvdeyen ?

**Comment by jfelchner** [comment]
@tvdeyen 

> I think since we have a solution here this can be closed out yes? It seems like there isn't much traction on it anyway.

https://github.com/rspec/rspec-rails/issues/1226#issuecomment-392351654

**Comment by tvdeyen** [comment]
I don’t think this is solved yet, but the work around has worked for me. Closing, though
