### ISSUE TITLE
type: :feature option causes module inclusion to fail

### ISSUE THREAD

**Issue by siruguri** [rspec/rspec-rails#1268]
I am not sure where the problem lies... whether with RSpec, rspec-rails or Capybara. I found one discussion on SO where someone had the same problem, so I'm posting it as an issue in case it's actually reproducible.

So the basic symptom is that Capybara DSL isn't being recognized unless it's explicitly included in `RSpec.configure`. And the problem is that in `RSpec.configure`, this works:

    config.include Capybara::DSL

but this doesn't:

    config.include Capybara::DSL, type: :feature

My features are in `spec/features` as `*_spec.rb` files. The error is (for both `rake spec` and for `rake spec:features`):

    Failure/Error: visit '/'
    NoMethodError:
       undefined method `visit' for #<RSpec::ExampleGroups::IncomePage::Individual:0x007fece82c97c8>

I appear to have the latest release versions of everything:

    rake --version
    rake, version 10.3.2

From my `Gemfile.lock`

    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-rails (3.1.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)

**Comment by myronmarston** [comment]
This is by design.  In RSpec 2, specs were automatically tagged with `:type` metadata based on their location in the file system.  This was very implicit and "magical" and could lead to confusing errors (for example, if the user put a model spec in `spec/model/my_model_spec.rb` rather than `spec/models/my_model_spec.rb` it would not work properly).

In RSpec 3, the spec-type inferrence based on file location is disabled by default.  Instead, we recommend you explicitly tag the spec type of each example group:

``` ruby
RSpec.describe "My feature spec", type: :feature do
  # ...
end
```

If you really prefer the spec type inferrence you can opt-in to that instead:

``` ruby
RSpec.configure do |c|
  c.infer_spec_type_from_file_location!
end
```

...although we recommend against that.

For more info, read our [announcement](http://myronmars.to/n/dev-blog/2014/05/notable-changes-in-rspec-3#filetype_inference_disabled_by_default) about this change a while back.

**Comment by siruguri** [comment]
Your promptness is awesome. I've posted your announcement to the couple of SO posts I found that discuss this.
