### ISSUE TITLE
describing a class defined within a helper causes "wrong argument type Class (expected Module)"

### ISSUE THREAD

**Issue by pdswan** [rspec/rspec-rails#1339]
```ruby
module SomethingHelper
  class InternalClass
    def help
      ...
    end
  end

  def help
    InternalClass.new.help
  end
end
```

```ruby
require 'spec_helper'

describe SomethingHelper, type: :helper do
  describe SomethingHelper::InternalClass do
      it "helps" do
        ...
      end
  end
end
```

**Comment by JonRowe** [comment]
Can you post the output of this too?

**Comment by cupakromer** [comment]
I'm not sure this is something we should support.

Metadata is inherited by nested example groups and examples. An example group with metadata `type: :helper` has specific meaning in rspec-rails. By writing the inner child class' specs as a nested example group it inherits the `type: :helper` metadata. However, it is _not_ an example group for a helper.

My suggested course of action would be one of the following:

- Implicitly test the inner class via the helper's methods
- Break the inner class' specs into a new top-level group or even it's own spec file

I did notice that even if the `type` is overwritten in a nested context it still has the same problem. This is because the parent example group class, which the nested example group class is a child of, has already included the `HelperExampleGroup`. Changing the metadata after the fact won't change that. Due to this,   making changes to the helper group behavior makes me a little concerned what other issues it will cause because of wiring to the inner workings of Rails land.

**Comment by cupakromer** [comment]
Ah I see there's a PR with some work around. Cross posting there.
