### ISSUE TITLE
invalid option: --pattern [regression?]

### ISSUE THREAD

**Issue by plentz** [rspec/rspec-rails#1343]
Hi! I was using rspec-rails `3.2.1` to test @plentz/lol_dba and I was receiving a weird error(`invalid option: --pattern`) [when testing](https://travis-ci.org/plentz/lol_dba/builds/55313195) against rails 3.2 + ruby 2.0 and 2.1 - but ruby 2.2 was working

I needed to rollback to rspec-rails `3.0.2` and [it's working again](https://travis-ci.org/plentz/lol_dba/builds/55315700). Looks like some kind of regression, I think.

**Comment by plentz** [comment]
Looks like isn't just me sensu/sensu/issues/779

**Comment by myronmarston** [comment]
Generally speaking, this happens when either the test-unit or minitest test runners are loaded.  They have their own CLI option parsers that emit errors when you use RSpec-specific CLI options.  The question is...why is the minitest or test-unit runner getting loaded?  In the past we've had users report this issue and it turned out to be that one of the gems they were using was loading the alternate runner.  I think there's also been some recent changes with how rails integrates with T::U/MT that may cause this issue as well.  @cupakromer, any ideas?

**Comment by cupakromer** [comment]
From what I can tell this is your the relevant setup:

- Ruby 2.0 - 2.2
- Rails 4.2.0
- [minitest gem (5.5.1)](https://github.com/plentz/lol_dba/blob/bd6ba024618ddf495e641c542450c7389d074bdb/Gemfile.lock#L66)
- [test-unit gem (3.0.9)](https://github.com/plentz/lol_dba/blob/bd6ba024618ddf495e641c542450c7389d074bdb/Gemfile.lock#L126)

It looks like you are including the `test-unit` gem in your [gemspec](https://github.com/plentz/lol_dba/blob/bd6ba024618ddf495e641c542450c7389d074bdb/lol_dba.gemspec#L27).

Is there a reason you are including both the `minitest` and the `test-unit` gems?

Including the `test-unit` gem is the source of this issue. Our [check](https://github.com/rspec/rspec-rails/blob/fba0669b86d2d1c65b3efc7b14703046cbbe200e/lib/rspec/rails/adapters.rb#L8-L69) is not handling the case where you have `test-unit` and `minitest` gems setup. I'm not sure this is a case to support unless there's a valid reason to have both gems that I am unaware of.

**Comment by plentz** [comment]
that was added probably to test against ruby 2.2 and rails 3.2. I've just removed the dependency of `test-unit` in the gemspec and moved it to the Gemfile and it's working again, but I really don't understand why.

**Comment by cupakromer** [comment]
Glad to hear things are now working :heart: I'm going to close this, if you feel there is something more rspec-rails should be doing please let me know.
