### ISSUE TITLE
What do you think about dividing a scenario into subsections?

### ISSUE THREAD

**Issue by vizcay** [rspec/rspec-rails#1352]
Let's say I have a big test suite of feature specs (capybara + poltergeist) where I test a bunch of complex stuff, for example spec/features/payment_spec.rb which has 15 scenarios.

At the beginning, I was doing a "visit xxx_path" before each scenario. But xxx is quite a complex page to build, that takes 500ms in development and a full 1sec to leave the capybara visit method (poltergeist setup I guess). That alone added 15secs of running time, plus the actual stuff, multiply that for a lot of other pages.

Then I read that is common in feature specs to test 4 or 5 related things for performance reasons, and because most of my scenarios don't have *hard* interdependencies I grouped them, let's say in 3 related scenarios which reduced the running time considerably. To divide the code, where it used to be a new scenario, I usually add a "comment line separator".

But now, when a test fails, I only get the "general" scenario description, to see what failed specifically I have to go inside the code and look what the code was doing or guess it by the failed line. Also, running with the "--format doc" is not the same at all (big fan of doc format).

Now I'm thinking.. given that we all accept that sometimes for performance reasons is sensible to test multiple things in a single scenario (we do, right? =), why can't rspec support this?

```ruby
feature 'payments' do
  scenario 'complete payment' do
    visit payments_path
    section 'fill header' do
      fill_in ...
      expect(page).to ...
    end
    section 'append checks' do
      select ...
      expect(page).to ...
    end
    section 'approve transaction' do
      click_on
      expect(page).to ...
    end
  end
end
```

Of course you can replace section with whatever keyword.. basically it's an "it" nested within another "it". If one fails, none of the following ones run. But this will allow to document exactly what the code was doing when failed.

Also this can be done with a shared before :all and forcing the scenarios to run in order not random, but I really feel this syntax describes better the code intentions.. what do you think? this should go to rspec-core?

**Comment by cupakromer** [comment]
@vizcay thanks for taking the time to write such a detailed description of your feature request :smiley_cat: (see [TLDR;](#tldr-options) and https://github.com/rspec/rspec-expectations/issues/733)

In regards to testing multiple things in one spec, this isn't limited to just features specs. Much of the older documentation does show a single expectation per spec. However, many of us feel the intent of that "rule" was to "test one behavior"; where a behavior can be defined across multiple expectations. It is also true that when one expectation fails only the failing expectation is the message reported.

In RSpec 2.x the only way around this was to write a custom matcher. I feel this limitation further encouraged the "one expectation per spec" philosophy instead of the "test one behavior" :frowning:. Now in RSpec 3.x we have [compound and composable matchers](http://rspec.info/blog/2014/01/new-in-rspec-3-composable-matchers/). Much work has been done to improve the output and failure messages when using these. I believe that feature was a big win, more easily allowing for testing a complete idea of the single behavior instead of breaking each sub-expectation into a different spec.

Coming back to feature specs, as your example illustrates one common use for them is testing "workflows". This often spans across pages. The composable matchers, while still useful, does not fully solve the multi-expectation scenario in these cases.

One thing about `feature` specs is that they are not really provided by rspec-rails. rspec-rails does provide the base type module. However, the core functionality and the `feature`, `scenario`, etc DSL is all provided by Capybara. Any change to that DSL specifically will need to come from Capybara.

Introducing the concept of a nested `it` isn't something we are currently looking to start supporting. The complexity it would create out does not justify it's use over simply using `before(:all)`, `context`, and `it`. Adding the feature also means the formatters would need to learn a new concept, which would be a breaking change and have to wait until RSpec 4; which is currently a ways away.

I don't want you to think I'm just dismissing this feature. I fully appreciate the problem it is trying to solve :blue_heart: :blue_heart:. I'd like you to know that one thing we are trying hard to do is streamline our feature set to focus on the core behavior. At the same time we are also encouraging the community to develop extension gems. We are always happy to see an extension gem gain popularity :smiley_cat:. We are very open to evaluating popular extensions and bringing them into our core libs (such as with rspec-fire).

<a name="tldr-option" id="tldr-option">**TLDR;**</a> so what are the options moving forward:

- please comment on a new feature we are considering `aggregate_failures`: https://github.com/rspec/rspec-expectations/issues/733
- create an rspec extension gem :heart: which adds your feature
- use `before(:all)`, `context` and `scenario`; you can create aliases for [groups](https://www.relishapp.com/rspec/rspec-core/v/3-2/docs/example-groups/aliasing) and [examples](https://www.relishapp.com/rspec/rspec-core/v/3-2/docs/configuration/create-example-aliases) to make easy simple custom DSLs
- write custom matchers
- add custom failure messages to expectations:

  ```ruby
  expect(page).to include("I'm sorry Dave"), "Hal is offline"
  ```

  As the custom failure message is inside the `it` block, it has access to everything the spec does. So you can string interpolate additional information in it.

**Comment by myronmarston** [comment]
To expand on what @cupakromer, it would be pretty easy to write an extension gem that adds this.  As of rspec/rspec-core#1869, RSpec's reporter now supports the publication of custom events, so your extension gem could define `section` to publish `:example_section_started` and `:example_section_finished` events:

``` ruby
module ExampleSections
  def section(name)
    RSpec.configuration.reporter.publish(:example_section_started, :name => name)
    yield
  ensure
    RSpec.configuration.reporter.publish(:example_section_finished, :name => name)
  end
end

RSpec.configure do |c|
  c.include ExampleSections
end
```

Your extension gem could then ship with a custom formatter that handled those events and printed it in the output.  If you decide to build an extension gem and want help or input from us, let us know!

**Comment by vizcay** [comment]
Thank you all for your good feedback, unfortunately I haven't a lot of time lately for this.
I'm currently looking at https://github.com/LRDesign/rspec-steps that looks like what I'm looking for.
