### ISSUE TITLE
expect(nil).not_to be_a_new(Object) passes

### ISSUE THREAD

**Issue by kWhittington** [rspec/rspec-rails#1362]
I stumbled on this debugging specs that should have failed passing. I was using the matcher to test saving of a new record by a controller action.

My example code was something like this:
```ruby
it 'creates a record' do
  action
  expect(assigns(:instance_variable)).not_to be_a_new(CustomObject)
end

# and

it 'does not create a record' do
  action
  expect(assigns(:instance_variable)).to be_a_new(CustomObject)
end
```

I was just poking around this controller action and swapped the tests but `creates a record` passed. I started looking at variables around the code and got a `'nil'` from `puts assigns(:instance_variable)`. Then to confirm I wrote a spec with an explicit `nil`:
```ruby
it 'thinks nil is not a new CustomObject' do
  expect(nil).not_to be_a_new(CustomObject)
end
```
Then confirmed the inverse will fail.
```ruby
it 'does not think nil is a new CustomObject' do
  expect(nil).to be_a_new(CustomObject)
end
```

Since I can't trust the matcher, I'm going to have to stop using it. Figured I'd make an issue to at least see if the errors on my end.

Thanks.

**Comment by cupakromer** [comment]
@kWhittington thank you for reporting this. :heart: 

I see why the behavior you experienced is confusing. The `be_a_new` matcher is a custom compound matcher checking:

```ruby
actual.is_a?(CustomObject) && actual.new_record?
```

When given `nil`, the matcher stops on the type check. In the positive this works as expected. However, when you negate it you simply are checking to see if the matcher failed. Since `nil` is not of type `CustomObject` the matcher treats it as the failure case which `not_to` sees as passing.

The matcher also supports an optional `with` chain providing a hash of expected attributes. I'm not sure what the proper semantics should be aside from a simple negation of the positive in this instance:

```ruby
expect(obj).not_to be_a_new(CustomObject).with(name: "RSpec", location: "Somewhere")
```

There is an additional matcher: `be_new_record` which will fail on `nil`:

```ruby
expect(nil).not_to be_new_record
# => expected  to respond to `new_record?`
```

At this point I'm not completely sold on that `nil` should cause `not_to be_a_new(Class)` to fail. If we do change that, it will need to wait until rspec-rails 4 as it would be a fundamental change to the matcher logic.

In the meantime, I believe what you want is a hybrid of positive type and negative state. You can achieve this with the following in RSpec 3:

```ruby
expect(assigns(:instance_variable)).to be_a(CustomObject).and(be_persisted)
```

You could make this a custom matcher helper via:

```ruby
def be_a_persisted(klass)
  be_a(klass).and(be_persisted)
end
```

Thoughts?

**Comment by JonRowe** [comment]
I'd expect this:

```Ruby
expect(nil).not_to be_a_new(CustomClass)
```

To pass, which it does, because it isn't a new `CustomClass`! So I don't think theres an issue here.

**Comment by kWhittington** [comment]
I see what you mean. I think the type being there implies some sort of type checking though.

`expect(object).not_to be_a_new(CustomObject)` tells me `object` is a `CustomObject` instance that's not been saved to the database. It's misleading to let the negation affect the type checking and the matcher's literal function (testing whether or not an `ActiveRecord::Base#persisted?` returns `true`).

@cupakromer I think you're going along the right lines here. I shouldn't double-up checks out, and should test for persistence and type separately.

I think the current functionality seems more like a "gotcha!" than anything else. I'm not sure many people would see this matcher, read the doc (`Passes if actual is an instance of model_class and returns false for persisted?.`), and want to make sure an object isn't saved to the database and also happens to not have a particular class type.

```ruby
describe Cat do
  context 'when invalid' do
    it 'cannot be saved and is not a dog' do
      expect(invalid_cat).not_to be_a_new(Dog)
    end
  end
end
```

You guys do also note it should be avoided though. I should have paid more attention to the examples on the [relish doc site](https://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/matchers/be-a-new-matcher) and I would have caught the behavior.

Thx for the tip!

**Comment by JonRowe** [comment]
> expect(object).not_to be_a_new(CustomObject) tells me object is a CustomObject instance that's not been saved to the database. 

You're reading it slightly wrong then as "to not be a new CustomObject" literally this means it's not a `CustomObject` that returns true for `#new_record?` which `nil` isn't (as it's neither a `CustomObject` nor does it return true for `#new_record?` so this is the correct behaviour.

You're looking for a different case `expect(object).to be_a(CustomObject).and be_persisted`.
