### ISSUE TITLE
Rspec-rails 3.2.1 - rspec-expectation specs failed on it block

### ISSUE THREAD

**Issue by veera** [rspec/rspec-rails#1370]
It's a Rails 4.2.1 app with rspec-rails 3.2.1. For example consider a sample user notifier email

user_notifer.rb
```
class UserNotifier < ApplicationMailer
  def welcome(recipient)
    @user = User.find(recipient)
    mail(to: @user.email, subject: 'welcome')
  end
end
```

user_notifier_spec.rb

```
require "rails_helper"

RSpec.describe UserNotifier, type: :mailer do
  let(:recipient) { double(:recipient) }
  let(:user) { double(:user, email: 'user@example.com') }

  subject { described_class.welcome(recipient) }

  it "welcome email" do
    expect(User).to receive(:find).with(recipient).and_return(user)
    subject
  end
end
```

When i run this spec, it got failed
![screen shot 2015-05-18 at 9 34 59 pm](https://cloud.githubusercontent.com/assets/362066/7680066/2504df4e-fda6-11e4-8f19-e996fd616ad8.png)

when i was debugging, it looks subject didn't called
![screen shot 2015-05-18 at 9 39 22 pm](https://cloud.githubusercontent.com/assets/362066/7680105/9e8217ce-fda6-11e4-9ff7-52a3def6aee0.png)

I'm not sure, what was the problem for this issue?

**Comment by cupakromer** [comment]
You've run into an edge case with the "magic" of `ActionMailer`. Your subject is not actually creating the mailer instance and calling `welcome` on it. It is instead creating an `ActionMailer::MessageDelivery` object.

The reason this "appears" to work in pry is that when you inspect the `subject` object `ActionMailer` actually instantiates the mailer instance and sends the message. Since pry uses `inspect` to display the value of a LOC, you get the behavior you see.

You should call `deliver_now` per the [`ActionMailer` API](http://guides.rubyonrails.org/action_mailer_basics.html#calling-the-mailer) if you would like to create the mailer object.

Also note that your actual code will get a warning from Rails the way you are using `User.find` with an instance of a user object:

```
DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`. (called from block (2 levels) in <top (required)> at /project/path/spec/mailers/user_notifier_spec.rb:16)
```

However, since you are stubbing this call, you will not see the warning in your spec output.

**Comment by veera** [comment]
@cupakromer Thanks for your updates, yes it was specific to ActionMailer, similar specs for other objects/services(except ActionMailer object) were working fine.
