### ISSUE TITLE
rspec-rails should be configured by default to not be run on RAILS_ENV=production

### ISSUE THREAD

**Issue by mauriciogracia** [rspec/rspec-rails#1382]
The file spec_helper.rb should contain some similar to this

```
raise "Not in test" unless ENV['RAILS_ENV'] == "test"
```

I suggest this since many tests start by truncating all the tables and if you by mistake run this on the production environment, well all your data will be lost

Hope someone else finds this useful and decides to include some default measures to avoid this from happening to somebody else

**Comment by myronmarston** [comment]
IMO, rspec-rails should allow users to run RSpec with alternate values for `RAILS_ENV`.  For example, for using a parallel test runner the user may want to run it with `RAILS_ENV=test_1` and another process with it set to `test_2`, etc.

I think it could make sense to add a line that raises if `ENV['RAILS_ENV'] == 'production'` since that's obviously dangerous.
