### ISSUE TITLE
"old `:should` syntax" warning message generating a json

### ISSUE THREAD

**Issue by soyellupi** [rspec/rspec-rails#1392]
When I run tests that execute a json build, rspec warnings me with the message

Using `#<Object:0x007f9152b90df8>` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/franciscolupionvillegas/projects/domestika_projects/domestika/app/controllers/concerns/user_helpers.rb:199:in `block (3 levels) in recommended_users_for'.

The json that I'm building use should as old rspec syntax
```
    Jbuilder.encode do |json|
      json.should do
        json.set! 'testing', true
      end
    end
```

It is confusing rspec syntax with jbuilder syntax

I'm using rspec-rails v3.2.3 and capybara 2.4.4

**Comment by myronmarston** [comment]
The warning will go away, and it'll allow Jbuilder to have the `should` method if you configure RSpec to disable the `should` syntax:

``` ruby
RSpec.configure do |rspec|
  rspec.expect_with :expectations do |expectations|
    expectations.syntax = :expect
  end
end
```

Alternately, you can disable all RSpec monkey patching with one line of config:

``` ruby
RSpec.configure do |rspec|
  rspec.disable_monkey_patching!
end
```

That may disable APIs you are relying on, though.

This issue is an example of the sorts of issues our old global monkey patches can cause, and shows why we are moving away from them :).

**Comment by soyellupi** [comment]
Very useful and very good explanation.

Thanks a lot!
