### ISSUE TITLE
Is ActionController::TestCase::Behavior.tests supported?

### ISSUE THREAD

**Issue by jaredbeck** [rspec/rspec-rails#1401]
The [`tests`][1] method 

> Sets the controller class name.  Useful if the name can't be inferred from test class.

Does rspec-rails support this method?

Consider these two controllers *which have the same name*:

```ruby
# app/controllers/a_controller.rb
class AController < ApplicationController; end

# app/controllers/x/a_controller.rb
module X
  class AController < ApplicationController; end
end

# spec/controllers/a_controller_spec.rb
RSpec.describe AController do
  # Will always test ::AController, no problem
end

# spec/controllers/x/a_controller_spec.rb
module X
  RSpec.describe AController do
    # Will either test ::AController or ::X::AController, 
    # depending on which has been autoloaded
  end
end
```

In minitest the solution is [`ActionController::TestCase::Behavior.tests`][1], e.g.

```ruby
module X
  class AControllerTest
    tests ::X::AController
  end
end
```

Does rspec-rails support the [`tests`][1] method?  I ask because it doesn't seem to work.

I am using rspec-rails 3.3.1.

[1]: http://api.rubyonrails.org/classes/ActionController/TestCase/Behavior/ClassMethods.html#method-i-tests

**Comment by myronmarston** [comment]
Warning: non-rails dev weighing in here (the last rails version I seriously used was Rails 2.3), so take my ramblings with a grain of salt.

It seems to me that `tests` exists to address the fact that rails testing w/ minitest _infers_ the controller from the test class name using an implicit mechanism.  `tests` allows you to explicitly pass the controller you intend to test.

RSpec already provides a way to explicitly specify what controller you are testing.  The method is called `describe` instead of `tests`.  If you want to call `tests ::X::AController` why not just call `describe ::X::AController`?

I think it would be confusing for users for RSpec to support two APIs for specifying the class-under-test, so I personally don't think it makes sense for rspec-rails to support `tests`.  It's probably worth documenting it somewhere, though.

**Comment by JonRowe** [comment]
Short answer, no `rspec-rails` doesn't provide this method, but we give you the option to specify the controller name in the description instead.

**Comment by cupakromer** [comment]
Rails autoloading is fraught with issues. Additionally, testing single files without loading everything is something we are nudging people toward. My suggestions are:

- require the explicit controller (this is actually a good idea for us to consider adding to the scaffold generators)
- specify the full class name (the scaffold generator does this currently)

  ```ruby
  RSpec.describe X::AController, type: :controller
  ```

  if you wanted to use the `X` scope you could do:

  ```ruby
  module X
    # I don't think the :: prefix is necessary, but it will make it explicit
    RSpec.describe ::X:AController, type: :controller do
    end
  end
  ```

Be aware that any module you call while in `module X` in the spec will not autoload `X::AModel` if there already is `::AModel` loaded. It's the same Rails autoload problem at hand.

**Comment by cupakromer** [comment]
See also:

- http://urbanautomaton.com/blog/2013/08/27/rails-autoloading-hell/
- http://guides.rubyonrails.org/autoloading_and_reloading_constants.html
- http://cirw.in/blog/constant-lookup.html

**Comment by jaredbeck** [comment]
> Rails autoloading is fraught with issues. 

100% agree. ActiveSupport autoload is inaccurate; once it finds a match, it doesn't keep looking to see if there's a better match. I'll create an issue on AS.

> If you want to call tests ::X::AController why not just call describe ::X::AController?

Yes, that works.  However, doesn't this have the same problems (http://techblog.thescore.com/how-you-nest-modules-matters-in-ruby/) that module shorthand always has in plain ruby?

> My [suggestion]: require the explicit controller

Yes, that is the solution I went with, because I prefer module nesting to module shorthand.

I'll close this issue, as you've answered my question, thanks!

**Comment by jaredbeck** [comment]
> ActiveSupport autoload is inaccurate; once it finds a match, it doesn't keep looking to see if there's a better match. I'll create an issue on AS.

Issue created: https://github.com/rails/rails/issues/20621

**Comment by cupakromer** [comment]
> However, doesn't this have the same problems (http://techblog.thescore.com/how-you-nest-modules-matters-in-ruby/) that module shorthand always has in plain ruby?

Yes and no. `RSpec.describe` is just a method call to which you pass a value. It's no different than any other method call, the same goes for how the passed parameter is resolved. It just happens that in this case we are passing it a constant reference to a class. The scope in which we send `RSpec.describe` defines the constant lookup rules. Take a look at the following three examples:

- Example 1: A standard spec setup
  ```ruby
  self           # => main
  Module.nesting # => []

  RSpec.describe ::X::AController do
    self            # => RSpec::ExampleGroups::XAController
    described_class # => X::AController
    Module.nesting  # => []
  end
  ```
- Example 2: A standard nested spec setup
  ```ruby
  module X
    self           # => X
    Module.nesting # => [X]

    RSpec.describe AController do
      self            # => RSpec::ExampleGroups::XAController
      described_class # => X::AController
      Module.nesting  # => [X]
    end
  end
  ```
- Example 3: Nesting with explicit constant passed to `describe`
  ```ruby
  module X
    self           # => X
    Module.nesting # => [X]

    RSpec.describe ::X::AController do
      self            # => RSpec::ExampleGroups::XAController
      described_class # => X::AController
      Module.nesting  # => [X]
    end
  end
  ```

Notice that all three examples resolve the `described_class` to the same constant: `::X::AController`. Likewise, `self` in the example groups all resolve to the same generated spec class name of `RSpec::ExampleGroups::XAController` where the `XAController` matches the `described_class` constant sans separators.

I can see two things that may be confusing, please let me know if there are more:

- In the last two examples, while the scope is `X`, the created example group is not nested under it
- Even though the example group block is run in the context of the created example group class, the constant resolution in the block is performed based on the scope the block was defined in

The first bullet is designed to not pollute your modules and namespaces while running specs. The second bullet is just Ruby's quirky constant resolution rules.

**Comment by cupakromer** [comment]
FWIW I think these are very good questions. I am going to take this and convert it into a new blog post for the [rspec.info](http://rspec.info) site.

**Comment by cupakromer** [comment]
Additionally, I see several things to improve the rspec-rails generators:

- The scaffold generator creates both a model and controller; since it creates both any nesting done guarantees that we know the proper scope of the model and the controller; it also means we should require both files explicitly
- Possibly more controversial with scaffold generators, we could provide the proper module nesting to eliminate the need to provide the fully qualified name of the model in the generated controller spec...I'll need to double check what Rails does by default in the controller though; I'd prefer to simply mirror the two
- For a controller generator we can add a helpful comment explaining module name-spacing (only if the controller namespace is nested) with possible links to the aforementioned blog posts after publishing

**Comment by jaredbeck** [comment]
Those examples, and the explanations of the rationale were really helpful, thanks Aaron!  I see now why rspec-rails doesn't need to support the `ActionController::TestCase::Behavior.tests` method.
