### ISSUE TITLE
Option not to pluralize feature name on generation

### ISSUE THREAD

**Issue by carlesjove** [rspec/rspec-rails#1403]
When generating a `feature` with `rails g rspec:feature` its name is always pluralized. Sometimes this leads to undesired results, such as `user_manages_account` being pluralized into `accounts`. The description within the spec file will be pluralized, too. This requires renaming the file plus editing the description.

I would expect the generator *not* to pluralize the name.

However, it'd be also nice if a `singular` or `no-pluralize` option could be passed.

I could try to implement this if it's accepted.

**Comment by cupakromer** [comment]
Did you manually generate the associated controller / models or use a generator?

**Comment by carlesjove** [comment]
For features, I always generate them independently, so I run `g rspec:feature`.

**Comment by cupakromer** [comment]
@carlesjove yes, I see what you are saying. I agree I do not think pluralizing the name is generally what you want for a feature spec. Additionally, I think it would be nice to be able to provide it a string description which it would properly handle in the file name as well:

```console
$ bin/rails g rspec:feature "User manages account"
      create  spec/features/user_manages_account_spec.rb
```

I'm sure how useful additional options would be considering the generated file is very minimal:

```ruby
require 'rails_helper'

RSpec.feature "User manages account", type: :feature do
  pending "add some scenarios (or delete) #{__FILE__}"
end
```

Though I am always open to the community stating otherwise.
