### ISSUE TITLE
`uninitialized constant RSpec::Rails::FixtureSupport` in 3.3.x

### ISSUE THREAD

**Issue by PikachuEXE** [rspec/rspec-rails#1404]
Stacktrace: https://gist.github.com/PikachuEXE/9ebe703f11eeef625f4f
It seems it's just missing a `require`

**Comment by cupakromer** [comment]
How are you initializing rspec-rails?

Currently, parts of rspec-rails are not meant to be loaded individually. The main [`lib/rspec/rails.rb`](https://github.com/rspec/rspec-rails/blob/1fb6f9f642/lib/rspec/rails.rb) loads the dependencies in order:

```ruby
require 'rspec/rails/view_rendering'
require 'rspec/rails/matchers'
require 'rspec/rails/fixture_support'
require 'rspec/rails/example'
```

**Comment by PikachuEXE** [comment]
I am only requiring `rspec/rails` in `spec_helper`
I have updated [`my gist`](https://gist.github.com/PikachuEXE/9ebe703f11eeef625f4f) to include my `spec_helper` content

**Comment by cupakromer** [comment]
Looking at the stack trace this seems to be coming from `rspec-cells`:

```
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.2/gems/rspec-rails-3.3.2/lib/rspec/rails/example/rails_example_group.rb:5:in `<top (required)>'
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.2/gems/rspec-cells-0.2.3/lib/rspec/cells.rb:4:in `<top (required)>'
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.2/gems/rspec-cells-0.2.3/lib/rspec-cells.rb:10:in `block in <class:Railtie>'
	from /Users/PikachuEXE/.rvm/gems/ruby-2.2.2/gems/railties-4.1.11/lib/rails/initializable.rb:30:in `instance_exec'
```

It seems `rspec-cells` it trying to be the main hook into rspec-rails instead of having you manually require them after rspec-rails loads. They are also ad-hoc loading only parts of rspec-rails; which is not currently the intended way to load this lib.

Looks like this was [recently reported](https://github.com/apotonick/rspec-cells/issues/71) and has been [fixed](https://github.com/apotonick/rspec-cells/pull/72).

**Comment by PikachuEXE** [comment]
Thanks for your info
I can't upgrade it since it requires the upgrade of gem `cell`
So I fix this by setting `require` to `false` for `rspec-cells`, then require it after requiring `rspec/cells` in `spec_helper`
