### ISSUE TITLE
Assigns inside Helper spec always returns nil

### ISSUE THREAD

**Issue by roooodcastro** [rspec/rspec-rails#1449]
Whenever I call `assigns[key]` on my helper spec, it returns nil regardless of the key I use to access it.

My helper method assigns the variable `@barra`, and when I try to test it (after calling it), both of these return nil:

```
assigns[:barra]
helper.assigns[:barra]
```

Also, after inspecting it with pry, I noticed that the assigns is completely void of any trace of my variable. Manually setting `assign(:barra, some_value)` before the spec will make `assigns[:barra]` return `some_value`, instead of the value that was set during the helper's execution.

[I asked this on StackOverflow](https://stackoverflow.com/questions/32010698/assigns-in-rspec-helper-test-is-returning-nil) but got no responses.

Am I using it in a wrong way? [The docs](https://www.relishapp.com/rspec/rspec-rails/v/3-0/docs/helper-specs/helper-spec) only mention assigning the variable before and using it inside the helper, which is the other way around of what I want.

I'm using rspec-rails 3.3, Ruby 2.1.5 and Rails 4.1.12.

**Comment by JonRowe** [comment]
As far as I know `assigns` is intended to replicate the controller test method, e.g. a variable has been assigned for use in a view (or helper) and so isn't intended for bi-direction use like this, looking at your stack overflow question I'd argue you shouldn't be using a helper method like that at all, can I ask what it is you are trying to accomplish? If it's to DRY up your controller rendering then I'd suggest testing this via an anonymous controller (in a controller spec) and triggering the helper, otherwise I'd suggest refactoring your helper to use locals rather than instance variables.
