### ISSUE TITLE
Running all specs all the time

### ISSUE THREAD

**Issue by escobera** [rspec/rspec-rails#1461]
Hello folks,

I'm running into a strange problem. I was used to running single tests like this on version 2.X
```rspec ./spec/models/data_function_spec.rb:9``` and this would run only the test on line 9 of that file. 
Now on 3.0 when I do that it runs that test first but runs all the suite after that. 

Is this the expected behavior? I am using rails-master.

**Comment by myronmarston** [comment]
It is not expected behavior.  What version of RSpec are you on?

**Comment by escobera** [comment]
$ rspec -v
3.1.7

**Comment by myronmarston** [comment]
I believe we had some bugs related to this in 3.1.  Can you upgrade to the latest (3.3) and let us know if you're still seeing the bug?

**Comment by escobera** [comment]
Actually it looks like it is running some other tests.

This is the output of running only ```rspec```


```
.........................................................................................

Finished in 17.94 seconds (files took 1.14 seconds to load)
19 examples, 0 failures
```

The first 19 dots are green, all the rest is white. I don't have any test:unit tests on this project.


I can't update any further because I am on rails master (5.0.0.alpha) 

```
rspec-rails (~> 3.3.3) ruby depends on
      actionpack (< 4.3, >= 3.0) ruby
```

**Comment by escobera** [comment]
@myronmarston if you need any more info lemme know.

**Comment by myronmarston** [comment]
A reproducible example would certainly help.  I have no way to guess why you'd be getting some white and some green dots.

That said, we don't generally backport bug fixes to older minor releases.  We follow SemVer and try to make upgrades trivial so that we can just support the current minor release (which greatly cuts down on our maintenance) so the fact that you can't upgrade to 3.3 is a deeper problem that should perhaps be solved first.  @cupakromer, can you remind us why the rails version is pinned in such a way that allows someone on rails master to use rspec-rails 3.1 but not 3.3?

**Comment by escobera** [comment]
I'm sorry about this, found some code being loaded that included the seeds (which generated thewhite dots).

My main problem is fixed, although your aswer makes me wonder which version I should be using.

**Comment by JonRowe** [comment]
> @cupakromer, can you remind us why the rails version is pinned in such a way that allows someone on rails master to use rspec-rails 3.1 but not 3.3?

I can, Rails master isn't supported at all currently but we couldn't go and pin old versions.

**Comment by JonRowe** [comment]
@escobera if you run rspec with the documentation formatter e.g. with `-f doc` you'll see the specs run

**Comment by samphippen** [comment]
I'm going to close this as stale, @escobera if you can give us a clear reproduction case (simple rails app to clone) for this bug then feel free to re-open
