### ISSUE TITLE
Helper specs include the helper in the wrong order

### ISSUE THREAD

**Issue by lowjoel** [rspec/rspec-rails#1483]
When I define:
```ruby
config.action_controller.include_all_helpers = false
```

with the following controller hierarchy:
```ruby
BController < AController < ApplicationController
```

and corresponding helpers:
```ruby
ApplicationHelper
AHelper
BHelper
```

In a BController view, all helpers should look up BHelper, AHelper, then ApplicationHelper. That way BHelper and AHelper can override methods defined by ApplicationHelper (inspect the view context's singleton class ancestors)

In RSpec-Rails, the BHelper spec has ApplicationHelper included after BHelper, so overriding methods defined in BHelper never get called.

**Comment by JonRowe** [comment]
I think this is because we extend the view with `ApplicationHelper` when it's defined manually, as Rails doesn't include it by default, we could fix this on > 2.0 by using `prepend` but other than that it'd be hard to fix this. A work around is to include/extend `ApplicationHelper` into your helper manually yourself.

**Comment by JonRowe** [comment]
Actually I'm wrong because the view is an instance so we have no choice but to use extend, so the only way to fix this is the workaround I described above. Sorry!

**Comment by lowjoel** [comment]
Darn, alright then, thanks.
