### ISSUE TITLE
readability of a_collection_containing_exactly and confusing error message

### ISSUE THREAD

**Issue by Bartuz** [rspec/rspec-rails#1487]
`a_collection_containing_exactly` can be used in such example:
```
it { is_expected.to a_collection_containing_exactly(email1, email2) }` 
```
and it works like a charm but is unfriendly to read. I thought that maybe adding `eq` will make it more readable

```
it { is_expected.to eq(a_collection_containing_exactly(email1, email2)) }` 
```

which looks much better but raises confusing error message:

```
     Failure/Error: expect(subject).to eq a_collection_containing_exactly(email1, email2)

       expected: a collection containing exactly "b@b.pl", "c@c.pl"
            got: ["b@b.pl", "c@c.pl"]

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -(a collection containing exactly "b@b.pl", "c@c.pl")
       +["b@b.pl", "c@c.pl"]

     # ./spec/models/anything:36:in `block (4 levels) in <top (required)>'
```

**Comment by myronmarston** [comment]
`a_collection_containing_exactly` is an alias of the primary form, `contain_exactly`.  The primary form is phrased as a verb and is meant to be passed directly to `to`:

``` ruby
it { is_expected.to contain_exactly(email1, email2) }
```

`a_collection_containing_exactly`, OTOH, is phrased as a noun and is meant when being passed as an argument in a composed matcher expression or as part of a message expectation:

``` ruby
expect(Emailer).to receive(:send_emails_to).with(a_collection_containing_exactly(email1, email2))

expect { |b| Email.with_addresses(&b) }.to yield_with(a_collection_containing_exactly(email1, email2))
```

`eq(a_collection_containing_exactly(email1, email2))` fails as it should because `["b@b.pl", "c@c.pl"] == a_collection_containing_exactly("b@b.pl", "c@c.pl")` returns false.  The matcher _matches_ such an array but is not _equal_ to it.  `eq` can be used to make the matching of an argument in an expression more strict so that only `==` is used for matching rather than `===` or `==` (the default). So, for example, `include(Integer)` would match against `[1]` or `[Integer]` and if you are trying to specify the latter and don't want to allow it to pass with the former you could wrap `Integer` in `eq` or an alias to make it more strict: `include(an_object_eq_to(Integer))`
