### ISSUE TITLE
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated.

### ISSUE THREAD

**Issue by fernandomm** [rspec/rspec-rails#1524]
Not sure if this is a bug or just the expected behavior.

I'm getting the following deprecation warning in 3.4.0:

```
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c
| c.syntax = :should }` instead.
```

If i add c.syntax = :should to my spec_helper the deprecation warning isn't shown.

But if I use:

```
config.expect_with(:rspec) { |c| c.syntax = [:should, :expect] }
```

It will still show this deprecation warning although "should" syntax is explicitly enabled.

**Comment by myronmarston** [comment]
> It will still show this deprecation warning although "should" syntax is explicitly enabled.

That does indeed sound like a bug.  We do however have a test for this specific case -- see the last scenario here:

https://relishapp.com/rspec/rspec-expectations/v/3-4/docs/syntax-configuration#explicitly-enable-both-syntaxes

Any chance you could put together a repo with a reproduction?

**Comment by fernandomm** [comment]
Sure, the repository is here: https://github.com/fernandomm/should-bug

The message that you will get is:

```
Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/fernando/Sites/should-bug/spec/should_bug_spec.rb:6:in `block (2 levels) in <top (required)>'.
```

Test file: https://github.com/fernandomm/should-bug/blob/master/spec/should_bug_spec.rb

Code that explicitly enable syntax: https://github.com/fernandomm/should-bug/blob/cd407e3d04b79bbcfc7325a3d9f43f6c72e4be6a/spec/spec_helper.rb#L20

I'm also able to reproduce the bug in rspec-expectations ( my original error message ), but I guess this one should be enough.

**Comment by myronmarston** [comment]
Thanks for taking the time to put that together!

> The message that you will get is:
>> Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/fernando/Sites/should-bug/spec/should_bug_spec.rb:6:in `block (2 levels) in <top (required)>'.

I do indeed get that message, but that's not the deprecation you originally reported:

> Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead.

The deprecation you originally reported is from rspec-expectations, and has to do with the rspec-expectations' monkey-patched `should` syntax.  The deprecation you are actually getting is from rspec-mocks, and has to do with rspec-mocks' monkey-patched `stub`/`should_receive`, etc syntax.

To turn off the deprecation warning, you need to configure rspec-mocks:

``` ruby
config.mock_with :rspec do |mocks|
  mocks.syntax = [:should, :receive]
end
```

Sorry for the confusion!  Do you have any ideas for how we could make the warnings less confusing?

BTW, I'm curious to hear why you want to stick with the `:should` syntax.  We provide a [tool to upgrade](https://github.com/yujinakayama/transpec) so switching should not be difficult, and the `:should` syntax is slated for extraction into an external gem in RSpec 4 (so that RSpec 4 can be zero-monkey patching by default, w/ the choice to install a gem to get the old monkey-patching syntax).

**Comment by harlantwood** [comment]
@myronmarston when you said:

> To turn off the deprecation warning, you need to configure rspec-mocks:
> 
>     config.mock_with :rspec do |mocks|
>       mocks.syntax = [:should, :receive]
>     end

...that caused errors for me.  This is what worked for me:

```ruby
config.mock_with :rspec do |mocks|
    mocks.syntax = [:expect, :should]
end
```

**Comment by JonRowe** [comment]
He meant `:expect` not `:receive`
