### ISSUE TITLE
expect to change not working for has_many :through relationships

### ISSUE THREAD

**Issue by vanboom** [rspec/rspec-rails#1531]
```ruby
class Item
  has_many :children
  has_many :grandchildren, :through=>:children
end

In feature spec...
expect {
   ... click link to add grandchild to item
  item.reload
  puts item.grandchildren.count  # it works when this puts is added
}.to change(item.grandchildren, :count).by(1)
```

If you add a puts statement to print the grandchildren count, then the expectation will pass properly, otherwise it fails.

thanks!

**Comment by JonRowe** [comment]
Try `change { item.grandchildren.count }.by(1)` instead of the other form, I expect this is a reference issue, I imagine that the `item.grandchildren` passed into RSpec doesn't know item has been reloaded so isn't clearing the query cache, but the full `item.grandchildren.count` in the block does know about the `item.reload` and is invalidating the cache.

**Comment by soulcutter** [comment]
Closing since this is expected behavior and the solution is explained above.

**Comment by JonRowe** [comment]
@soulcutter I only think that is what is going on, mind leaving this open until @vanboom has a chance to comment again?

**Comment by soulcutter** [comment]
Sure, didn't mean to interfere. It just looked stale after a week

**Comment by vanboom** [comment]
So sorry, the issue was in my logic, not rspec.  Closing.
