### ISSUE TITLE
shared_examples with `js: true` are wrongfully included in `js: true` contexts 

### ISSUE THREAD

**Issue by ojab** [rspec/rspec-rails#1579]
In this test:
```ruby
RSpec.shared_examples :shared_test, js: true do
  it { expect(true).to eq(false) }
end

RSpec.feature 'Test feature' do
  context 'Test context', js: true do
    it { expect(true).to eq(true) }
  end
end
```
:shared_test examples are executed in `Test context`, although we're not including it.

**Comment by ojab** [comment]
(Reproducible in both 3.4.2 and git master)

**Comment by myronmarston** [comment]
This is working by design.  Shared group metadata was intended to be used for automatic inclusion in matching groups when the feature was first written.  It's a problematic design, though, and we plan to change it. See rspec/rspec-core#1790.

For now, you can work around it like so:

``` ruby
RSpec.shared_examples :shared_test do
  context "some context", js: true do
    it { expect(true).to eq(false) }
  end
end
```

By putting the metadata on a nested group instead of the shared group itself, it avoids the auto-inclusion.  Hopefully we'll implement the solution discussed in rspec/rspec-core#1790 soon.
