### ISSUE TITLE
Deprecation warning due to out dated rspec-core dependency

### ISSUE THREAD

**Issue by caspian311** [rspec/rspec-rails#1581]
When running rspec on my rails app I get a bunch of these deprecation warnings.

[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

It appears that rspec-core fixed the issue in v3.4.4 but latest stable rspec-rails is pulling in an earlier version that still uses the last_comment instead of the last_description method. From the gemspec it looks like you're pulling in the same version of rspec-core as the rspec-rails. So I'm guessing this issue will go away once you guys release a stable tagged 3.4.4 version of rspec-rails.

**Comment by myronmarston** [comment]
> From the gemspec it looks like you're pulling in the same version of rspec-core as the rspec-rails.

It depends on whether it's a pre-release or not.  For pre-releases (e.g. 3.5.0.beta1) the version must be exactly the same.  Otherwise, it just has to be at the same minor version (e.g.`3.4.x`).

So, as long as you are on rspec-rails 3.4.x, you should be able to run `bundle update rspec-core` to get rspec-core 3.4.4.  Have you tried that?

**Comment by caspian311** [comment]
Yes. Explicitly including the newer rspec-core or doing the bundle update as you suggested so that the Gemfile.lock will contain the newer rspec-core will get rid of the deprecation warnings. 

Thanks, closing...
