### ISSUE TITLE
Work out testing story for ActionCable

### ISSUE THREAD

**Issue by penelopezone** [rspec/rspec-rails#1606]
We currently don't have one, so we should definitely work out what the story is.

**Comment by NullVoxPopuli** [comment]
I made this ruby client for action cable: https://github.com/NullVoxPopuli/action_cable_client
could it help with testing action cable?

**Comment by samphippen** [comment]
Hi @NullVoxPopuli, thanks for the suggestion, but we're going to take RSpec in a slightly different direction to test with ActionCable 😄

**Comment by JonRowe** [comment]
Whats the official Rails line on this @samphippen ?

**Comment by samphippen** [comment]
Waiting for https://github.com/rails/rails/pull/23211 to be merged before I start investigating.

**Comment by palkan** [comment]
Hi, @samphippen!

I've extracted rails/rails#23211 into a gem and added RSpec support too – https://github.com/palkan/action-cable-testing.

**Comment by palkan** [comment]
@samphippen  @benoittgt 

Hey, folks! It's been a while...

Since [`action-cable-testing`](https://github.com/palkan/action-cable-testing) has been merged into Rails 6.0, we think it's time to take care of RSpec part)

The gem already has [RSpec support](https://relishapp.com/palkan/action-cable-testing/docs) (built using the same structure as `rspec-rails`), so it's gonna be pretty easy to merge it.

The main question for now is whether we should use the [RSpec 4.x branch](https://github.com/rspec/rspec-rails/pull/2071) or target the 3.x version?

**Comment by samphippen** [comment]
@JonRowe should we drop bundler 1.x support here as well?

**Comment by palkan** [comment]
> if this is intended as an Rails 6.0 only feature

Yep, it's Rails 6+.

Ok, thanks guys; we'll provide a PR for 4.x.x.

**Comment by JonRowe** [comment]
We merged support for this, closing.
