### ISSUE TITLE
instance_eval or class_eval does get executed while testing using rspec

### ISSUE THREAD

**Issue by kamal-github** [rspec/rspec-rails#1667]
I have Active Record Model `Plan` has a snippet - 
with possible names as `yearly`, `monthly` etc. so ideally it creates a two method on the go, running while i am running rails app, but not while testing with rspec and throwing exception `NoMethodError for class<some hex>`.

```
self.all.pluck(:name).each do |plan|
    
    instance_eval <<-STR
      def #{plan.downcase}
        where(name: "#{plan.downcase}").first
      end
    STR

    class_eval <<-STR
      def #{plan.downcase}?
        self.name.downcase == "#{plan.downcase}"
      end

      def #{plan.downcase}!
        self.name = "#{plan.downcase}"
        self.save!
      end
    STR
  end
```

**Comment by JonRowe** [comment]
Hi, we're going to need some more detail for this, but I'll hazard a guess of the bat, if your snippet is defined in the class, then it will run in development mode as you have data in the database to iterate over, but it won't work in test mode because your database is likely empty, so the block never runs.

**Comment by kamal-github** [comment]
@JonRowe in `before` block I am running `Plan.create: 'monthly'`, so test db has at least one record, so ideally it should create one method.

**Comment by JonRowe** [comment]
@kamal-github where is your snippet defined? If it's at the class level my guess still stands, as the class is loaded before any specs are executed.

**Comment by kamal-github** [comment]
Yes, It is defined at class level, and thanks for this knowledge. Any suggestion for testing this?

**Comment by JonRowe** [comment]
You could delay loading of your class until after the test (although Rails would make that hard) or not wipe the database.

It would probably be better to refactor this implementation, it may look like it works ok in development but in production you would likely be limited to the plans loaded at first boot (due to Rails class caching), which would be interesting... Use of instance_eval / class_eval for this isn't recommended either.

In my opinion, you may be better off implementing this using `method_missing` if you really need it to be dynamic, or properly hardcode it.

**Comment by kamal-github** [comment]
@JonRowe Thanks!
