### ISSUE TITLE
Hash returned instead of HashWithIndifferentAccess in a Request Spec

### ISSUE THREAD

**Issue by roberts1000** [rspec/rspec-rails#1683]
I have the following request spec example:

````ruby
RSpec.describe "user_info" do
  let(:user) { FactoryGirl.create :user, first_name: "Jim", last_name: "Jones" }

  it "allows indifferent access" do
    sign_in(user)
    controller.user_info # This returns an instance of HashWithIndifferentAccess
    get root_path
    controller.user_info # This returns an instance of Hash
    expect(controller.user_info[:first_name]).to eq("Jim")
    expect(controller.user_info["first_name"]).to eq("Jim")
  end
end
````

My application creates a `user_info` helper method which is available on controllers and views.  When `controller.user_info` is called before the `get root_path` line, I get an instance of `HashWithIndifferentAccess` back (which is what I'm expecting).  When I call `controller.user_info` after 'get root_path`, I get a regular `Hash` instance back (which ultimately causes the example to fail).

I'm using RSpec 3.5.1 on a Rails 4.2.7 application.

**Comment by JonRowe** [comment]
Hmm, without knowing how your code is creating the hash it's difficult to see why this would change, I think this is something provided by Rails rather than us also, could you try rewriting this spec into mini test (use the [rails bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb) to make it easier) and see if the same behaviour is exhibited?

**Comment by roberts1000** [comment]
Sure thing.  I'm not really a mini test guy so it'll take a little time to come up to speed, but I'll see what I can figure out.  Thanks for the feedback.

**Comment by roberts1000** [comment]
I was able to reproduce this with a very simple Rails app using minitest.  I'll follow up with Rails.
