### ISSUE TITLE
Rails 5: Using URL instead of action name in controller tests

### ISSUE THREAD

**Issue by jamesmarkcook** [rspec/rspec-rails#1756]
[Rails 5 now uses urls when making requests in controller tests.](http://blog.bigbinary.com/2016/04/19/changes-to-test-controllers-in-rails-5.html) For example, instead of:

```ruby
post :create, params: { person: { name: "James", age: 29 } }
```
the new practice would be to do this instead:

```ruby
post person_url, params: { person: { name: "James", age: 29 } }
```

This is possible to do with RSpec by using a `type: :request` spec. However, wouldn't it make sense to also allow this in `type: :controller` specs?

**Comment by JonRowe** [comment]
The type of test you're thinking of doesn't exist in Rails 5, controller tests are now integration tests (which are different) and you can't use `type: :controller` without the seperate `rails-controller-tests` gem. As you point out `type: :request` uses the same insides as the integration test in Rails, as does `type: :feature` I believe.

That said `post` is entirely provided by Rails so supports what they support where they support it, so if it doesn't work in `type: :controller` specs it's because the `rails-controller-tests` gem doesn't support it.

**Comment by jamesmarkcook** [comment]
Thanks for your reply and explanation.

I've read a lot of different approaches regarding Rails new testing philosophy and have become pretty confused as to what tests I should be writing and how these fit with RSpec.

However I think my confusion is with semantics. I'm a lot clearer now you've explained things. Rails 5 controller tests are integration tests, which in RSpec are `type: :request` specs, right? Or not? lol

So `type: :controller` specs are essentially for Rails 4 controller tests.

Just a suggestion but an explanation of this on the Relish docs for newbies or those unfamiliar with this change would be great! :)

**Comment by jamesmarkcook** [comment]
Ahh, I see there is a mention of this here: http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/#rails-support-for-rails-5

Still, my suggestion still stands. I think this should be easier to understand from the Relish docs. A mention of Rails 5 in the request and controller sections would be awesome!

Thanks again, and I will stop bothering you now.
