### ISSUE TITLE
NullPointerException in Jruby and Rspec with Tempfiles

### ISSUE THREAD

**Issue by synth** [rspec/rspec-rails#1773]
I've encountered an issue in Rspec when uploading fixture files that causes a NullPointerException in JRuby. 

I'm posting the issue here because the issue only becomes evident when I upload a fixture file across describe blocks in Rspec. When the code occurs in the same describe block, there is no issue. 

I'm testing with rspec-rails v2.13.2 and rails v3.2.22.2.

Here is the offending code:

````ruby
require 'spec_helper'

describe 'Tempfile' do
  let(:file) { fixture_file_upload(Rails.root.join('spec/fixtures/file_1.txt').to_s) }

  describe 'test' do
    describe '1' do
      it { expect{file}.to_not raise_exception }
    end

    describe '2' do
      # Test will pass if before block is uncommented
      # Or if config.order = "random" is commented in spec_helper
      # before { ActionMailer::Base.deliveries.clear }
      it { expect{file}.to_not raise_exception }
    end

  end  

end
````

I've also posted to jruby about this here: https://github.com/jruby/jruby/issues/4433
The sample app is here: https://github.com/synth/jruby-rspec-tempfile-bug
TravisCI builds are here: https://travis-ci.org/synth/jruby-rspec-tempfile-bug

**Comment by JonRowe** [comment]
Sorry but this is unlikely to be an RSpec bug, `fixture_file_upload` is a Rails (not RSpec) provided method but also JRuby tends to behave a bit differently to other Rubies and is prone to these sort of quirks, (in fact you can't ever get that error in MRI Ruby), you could try replicating this with plain classes and see if it's a JRuby bug otherwise I'd suggest trying the latest version of RSpec, `3.5.4`, as we don't support `2.13.2` and theres a painless upgrade path thanks to `2.99`.

**Comment by synth** [comment]
I think so as well, but I was considering the possibility that maybe rspec was doing some file handle cleanup across describe blocks that might account for this behavior.
