### ISSUE TITLE
undefined method `expectation_fulfilled?' for nil:NilClass

### ISSUE THREAD

**Issue by JasperWoo** [rspec/rspec-rails#1987]
Basically I am trying to mock `object` here:

    if (object.present? && object.deleted_at.nil?)

When I tried the canonical way:

    object = Object.new
    object....assign necessary fields
    object.deleted_at = nil
    object = double

Rspec throws:

    Failure/Error: method_name.to_s if ExpectationChain === chains.last unless 
    chains.last.expectation_fulfilled?
     
    NoMethodError:
    undefined method `expectation_fulfilled?' for nil:NilClass

When I tried the cheating way:

    something = double
    relation = double
    expect(something).to receive(:nil).and_return(true)
    expect(object).to receive(:present).and_return(true)
    expect(object).to receive(:deleted_at).and_return(something)

`(object.present? && object.deleted_at.nil?)` evaluate to `false` 

Huh? What should I do then?

**Comment by JonRowe** [comment]
To test this just changed the deleted_at attribute on your real object. 

```Ruby
object = Object.new
object.deleted_at = nil
```

**Comment by JasperWoo** [comment]
What you said is exactly what I did first (see post). And so it's still giving the same error. Would you mind first explaining what the error means before closing the issue?

**Comment by JonRowe** [comment]
Closed because there is nothing here related to `rspec-rails` here, its a request for help, please use the mailing list or stackoverflow, also note what I did is not the same, you overrode the object with a double (with `object = double` which is obviously causing trouble in something else in your code downstream)

**Comment by pjscopeland** [comment]
I have run into the same error message, and found that it could be treated as a failed expectation; though I was unable to isolate under what circumstances _this_ error came up instead of a more helpful failed expectation message.

There is very little information about it online... it's as if @JasperWoo and myself are the only two people to ever have seen it.

![Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

It does seem to be related to `rspec-mocks` though, as both of us were expecting certain messages to be received by things.

**Comment by JonRowe** [comment]
@pjscopeland @JasperWoo never actually supplied the code required to replicate anything, he has a bunch of typos in his specs and replaces his object with a double, none of which would cause the error but all would definitely not work, if you have a snippet that can reliably produce this error please share it and we will look into it more

**Comment by AntoineBecquet** [comment]
@pjscopeland I was able to pinpoint more closely where the error was coming from, but it seems related to rspec-mock : https://github.com/rspec/rspec-mocks/issues/1496
