### ISSUE TITLE
Per example group setting `use_transactional_fixtures` is named `use_transactional_tests` in contrary to global one

### ISSUE THREAD

**Issue by faucct** [rspec/rspec-rails#2008]
RSpec 3.7.0

```ruby
Failure/Error: self.use_transactional_fixtures = false

NoMethodError:
  undefined method `use_transactional_fixtures=' for RSpec::ExampleGroups::UtilsExclusiveRunner:Class
  Did you mean?  use_transactional_tests=
                 use_transactional_tests
                 use_transactional_tests?
```

**Comment by JonRowe** [comment]
You've come across an oddity in how rspec and rails work together, we have one global setting `use_transactional_fixtures` to match our parlance and how Rails used to talk about this. The equivalent Rails setting is called `use_transactional_tests` as they have their built in mini-test preference, neither are intended to be called at a per example level, and the later is only exposed due to Rails polluting the example namespace (which is unfortunately necessary). Sorry for the confusion.
