### ISSUE TITLE
`rails g rspec:install` doesn't add `config.generators.test_framework` setting

### ISSUE THREAD

**Issue by rlue** [rspec/rspec-rails#2220]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.0preview1
Rails version: 6.0.1
RSpec version: 3.9

## Observed behaviour

First...

```
$ rails new foo
# add rspec-rails to Gemfile
$ bundle
$ rails g rspec:install
```

then...

```
$ rails g scaffold posts
      ...
      invoke    test_unit
      create      test/controllers/posts_controller_test.rb
      create      test/system/posts_test.rb
      ...
```

## Expected behaviour

```
$ rails g scaffold posts
      ...
      invoke    rspec
      create      spec/controllers/messages_controller_spec.rb
      create      spec/views/messages/edit.html.erb_spec.rb
      create      spec/views/messages/index.html.erb_spec.rb
      create      spec/views/messages/new.html.erb_spec.rb
      create      spec/views/messages/show.html.erb_spec.rb
      create      spec/routing/messages_routing_spec.rb
      ...
```

Obviously this is achieved by adding the following line to the Rails application config:

```
config.generators.test_framework :rspec
```

but I am curious—is does the RSpec team consider this too much hand-holding? In my opinion, if it's not going to be provided automatically by the `rspec:install` generator, then it should at least be in the README.

**Comment by pirj** [comment]
I believe it's [here](https://github.com/rspec/rspec-rails/blob/be3ae66f25863e05336d7fb54b363a833179aa4c/lib/rspec-rails.rb#L21).

Can you reproduce this with `rspec-rails` version `4.0.0.beta3`?

**Comment by rlue** [comment]
Wow, that was fast!

It appears that in order to take advantage of this, I need to `require 'rspec-rails'` in `/config/application.rb`. Is this the correct approach? Is there another way to do it?

**Comment by pirj** [comment]
As far as I remember, putting this in `Gemfile` is sufficient:
```ruby
group :development, :test do
  gem 'rspec-rails', '~> 4.0' # in case of pre-release '4.0.0.beta3'
end
```

**Comment by rlue** [comment]
My goodness, you're right. I think when I tried it yesterday, maybe I hadn't run `spring stop`, so the generators were running based on the outdated application config? Thanks again for your insight.

**Comment by rlue** [comment]
Okay, one thing I just noticed is that the default generators still create controller specs, even though they are discouraged as of RSpec 3.5. 

I ended up adding the following line to my `config/application.rb`:

```ruby
generators.test_framework :rspec, controller_specs: false
```

Is this something that is worthy of fixing? Is a fix already planned for it? I can think of two ways:

1. disable controller specs from the generator by default; or
2. modify the `rspec-rails.rb` file you linked above to use this line instead.

**Comment by pirj** [comment]
Good point. This is something that https://github.com/rspec/rspec-rails/pull/2222 is about to address.                                                                                                                                                                                                                                                                                                                                                                                                                   From: Ryan LueSent: Sunday, 8 December 2019 07:13To: rspec/rspec-railsReply To: rspec/rspec-railsCc: Phil Pirozhkov; CommentSubject: Re: [rspec/rspec-rails] `rails g rspec:install` doesn't add `config.generators.test_framework` setting (#2220)Okay, one thing I just noticed is that the default generators still create controller specs, even though they are discouraged as of RSpec 3.5.
I ended up adding the following line to my config/application.rb:
generators.test_framework :rspec, controller_specs: false
Is this something that is worthy of fixing? Is a fix already planned for it? I can think of two ways:

disable controller specs from the generator by default; or
modify the rspec-rails.rb file you linked above to use this line instead.


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rspec/rspec-rails/issues/2220?email_source=notifications\u0026email_token=AAABWBDEHNT2YCNO4PVEQX3QXRX5FA5CNFSM4JV3UNTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGGVQBI#issuecomment-562911237",
"url": "https://github.com/rspec/rspec-rails/issues/2220?email_source=notifications\u0026email_token=AAABWBDEHNT2YCNO4PVEQX3QXRX5FA5CNFSM4JV3UNTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGGVQBI#issuecomment-562911237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
