### ISSUE TITLE
v4.0.0.beta3 regression when using mocha

### ISSUE THREAD

**Issue by ZeroPointEnergy** [rspec/rspec-rails#2252]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.6.5p114
Rails version: 6.0.2.1
RSpec version: 4.0.0.beta2

The application in question uses the mocha gem together with rspec-rails

## Observed behaviour

WIth 4.0.0.beta3 if I use something like this:
`Node.any_instance.stubs(:compiled_parameters).raises ParameterConflictError`
I get the following error:
`The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported`

## Expected behaviour

With 4.0.0.beta2 the same tests run flawlessly.

I bisected the issue and git pointed to 7ff7c3e291fcce6a4706bc45314ab2a50f72ffa9 as the first problematic commit.

The only added code outside of tests is `require 'rspec/rails/matchers/have_enqueued_mail'` which in turn does `require "rspec/mocks"`. This leads to the test now jumping into `rspec::mocks` (https://github.com/rspec/rspec-mocks/blob/master/lib/rspec/mocks/syntax.rb#L78) instead of using the method from the mocha gem.

**Comment by benoittgt** [comment]
Hello

Thank for your issue. Isn't weird to use both library? 🤔

Also `any_instance` is from the legacy `should`. A quick fix may be to disable it if you are not using. http://rspec.info/documentation/3.9/rspec-mocks/RSpec/Mocks/Configuration.html#syntax=-instance_method

We require rspec-mock here because we use `any_args` (from `RSpec::Mocks::ArgumentMatchers`) to build `args`. https://github.com/rspec/rspec-rails/blob/64b2712da9d12c03a582bb26b62337504f8d1b76/lib/rspec/rails/matchers/have_enqueued_mail.rb#L78-L80

I don't have any more idea. Maybe @JonRowe or @pirj will have some.

**Comment by ZeroPointEnergy** [comment]
I don't use `rspec::mocks`, I use `config.mock_with :mocha`. The issue if I understand it correctly is that `rspec::mocks` is now loaded anyways.

**Comment by pirj** [comment]
Wondering what is calling [`enable_should`](https://github.com/rspec/rspec-mocks/blob/master/lib/rspec/mocks/syntax.rb#L26), and if you can avoid this from being called @ZeroPointEnergy .

**Comment by JonRowe** [comment]
Er, hm, `rspec-rails` does use `rspec-mocks` (so it you use `rspec-rails` you do use `rspec-mocks`) but regardless `rspec-mocks` and `mocha` shouldn't be interfering with each other...

I'm not sure why you're getting out own scope error, it must be the require causing an overload, if you turn off monkey patching does it go away @ZeroPointEnergy ?

**Comment by ZeroPointEnergy** [comment]
If I disable monkey patching in the rspec configuration it doesn't even get to the test because something breaks long before that. The `should` syntax is enabled on purpose because a lot of tests are written this way in the application. It is a pretty old open source project I try to keep updated in my free time https://github.com/sodabrew/puppet-dashboard

**Comment by pirj** [comment]
Thanks for reporting this, I'm able to reproduce the issue.
It seems that removing `require 'rspec/mocks' from `lib/rspec/rails/matchers/have_enqueued_mail.rb` doesn't help much, as it's autoloaded on `include RSpec::Mocks::ExampleMethods` anyway.

The problem as I see it is that `rspec-mocks`' patch to `Class` is added before Mocha's.
I could quickly work around this like that:
```ruby
$LOAD_PATH.push File.dirname(__FILE__)

# Start collecting data for test coverage report
require 'simplecov'
require 'simplecov-console'
SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::Console,
])
SimpleCov.start 'rails' do

  add_filter '/spec/'
  add_filter '/.bundle/'
  add_filter '/vendor/'
  add_group 'Tasks', "lib/tasks"
end

# This file is copied to ~/spec when you run 'ruby script/generate rspec'
# from the project root directory.
ENV["RAILS_ENV"] = "test"
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require 'mocha/api'
require 'rspec/core'
require 'rspec/collection_matchers'

# Requires supporting files with custom matchers and macros, etc,
# in ./support/ and its subdirectories.
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}

# Uncomment to trace deprecation warnings
#ActiveSupport::Deprecation.debug = true

RSpec.configure do |config|
  config.mock_with :mocha
  config.prepend_before :each do
    verbosity = $VERBOSE
    $VERBOSE = nil
    SETTINGS = SettingsReader.default_settings
    $VERBOSE = verbosity
  end
  config.expect_with(:rspec) { |c| c.syntax = [:should, :expect] }
  config.include RSpecHtmlMatchers
end

require 'rspec/rails'

RSpec.configure do |config|
  config.use_transactional_fixtures = true
end
```

Can you please try it?

Another way is to:
```diff
# lib/mocha/api.rb
- Class.send(:include, Mocha::ClassMethods)
+ Class.send(:prepend, Mocha::ClassMethods)
```

That would mean that in 1.8.7 and 1.9 it will still break, however, this is not a problem with RSpec Rails 4, since those Ruby versions are not supported anymore. Should not be a problem for those who don't use `rspec-rails`, but do use Mocha, since  Mocks are not loaded in this case.

I believe the pull request should be sent to Mocks to only apply its patches if it's the mocking framework of choice.

**Comment by JonRowe** [comment]
Fix released in v.4.0.0.beta4
