### ISSUE TITLE
Polymorphic table association not changed but marked as changed

### ISSUE THREAD

**Issue by donmb1** [rspec/rspec-rails#2303]
```expected `model.edit_histories` not to have changed, but did change from #<ActiveRecord::Associations::CollectionProxy []> to #<ActiveRecord::Associations::CollectionProxy []>```

for this:

`expect { update_request(model) }.not_to change { model.edit_histories }`

My model is polymorphic. It works well for none polymorphic models.

Tried this to be on the save site:

`expect { update_request(model) }.to change { model.edit_histories }.by(0)`

And got this:

```expected `model.edit_histories` to have changed by 0, but was changed by []```

**Comment by pirj** [comment]
Can you please check if `expect { update_request(model) }.to change { model.edit_histories.count }.by(0)` works?

**Comment by donmb1** [comment]
that works

**Comment by pirj** [comment]
I suggest using this approach, since Rails is doing a lot under the hood with PORO, and `model.edit_histories` may actually change, even though e.g. the number of associations remains zero.
Specifically:
```
expect { update_request(model) }.not_to change { model.edit_histories.count }
```

Hope that works for you. Other guys may suggest better solutions to that but in general this is not something that can/should be fixed on `rspec-rails` side.

**Comment by JonRowe** [comment]
You could also try adding a `to_a`, ActiveRecord proxy objects are problematic for detecting changes as they can "change" whilst being semantically the same, as in this instance, it'll be a different object, but still empty.  We have some work on this in rspec-expectations but I'm not sure its complete enough to release.
