### ISSUE TITLE
Generated requests specs are not consistent with naming

### ISSUE THREAD

**Issue by eloyesp** [rspec/rspec-rails#2355]
We noticed while working on https://github.com/tpope/vim-rails/issues/368 , that generators does use a different naming scheme for requests specs.

For example, for a Posts Controller, the scaffold generator use [`spec/requests/posts_spec.rb`](https://github.com/rspec/rspec-rails/blob/master/spec/generators/rspec/scaffold/scaffold_generator_spec.rb#L9), while using the controller generator does create [`spec/requests/posts_request_spec.rb`](https://github.com/rspec/rspec-rails/blob/9fb6c9c482da29b8803dd6f17b34d37a6367b8f2/spec/generators/rspec/controller/controller_generator_spec.rb#L9).

There is a shared example for requests specs [here](https://github.com/rspec/rspec-rails/blob/9fb6c9c482da29b8803dd6f17b34d37a6367b8f2/spec/support/generators.rb#L46) that does use the first naming, that might be re-used everywhere to have a consistent naming scheme.

It seems like a minor issue, what are your opinions about this?

**Comment by pirj** [comment]
A fix is much appreciated. Thanks for reporting!

**Comment by klyonrad** [comment]
A more broad question @pirj @JonRowe 

Is there some basic idea about **when the spec files should get the type suffix and when not**?
Even when we don't answer that question I think that the file naming style for controller and request specs should be similar.

When I made the changes to favor the request specs (see PRs https://github.com/rspec/rspec-rails/pull/2262 and https://github.com/rspec/rspec-rails/pull/2288) I oriented myself on how the controller spec file names were and still are (`spec/controllers/foo_controller_spec.rb`).
It felt a bit off to me because it looks soo redundant but if you look at the scaffold generator you can see that this behaviour is also there for the routing specs and the view specs. The **exception** to this convention are the model specs 🤔

The thinking that I can come up with is that people often type in only a file name to open and it could become confusing when both the model spec files and are named similarly (`post_spec` and `posts_spec`)`

**Comment by JonRowe** [comment]
Controller specs are named `foo_controller_spec.rb` only because the classes are `FooController` if you are not in a direct 1 to 1 relationship with a class you don't need to be so strict about your naming, that said I'd probably still match it to the noun of the controller.

**Comment by klyonrad** [comment]
This is closed wih https://github.com/rspec/rspec-rails/pull/2378

**Comment by JonRowe** [comment]
Good spot, this should have been autoclosed.
