### ISSUE TITLE
Error running rspec in rails 6.1.1

### ISSUE THREAD

**Issue by pachun** [rspec/rspec-rails#2441]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]`

Rails version: `Rails 6.1.1`

RSpec version:

```
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.1
  - rspec-rails 4.0.2
  - rspec-support 3.10.1
```

## Observed behaviour

Running `bundle exec rspec` in a brand new rails 6.1.1 app after installing rspec as defined in the readme results in:

```
$ bundle exec rspec

An error occurred while loading ./spec/my_test_app_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

LoadError:
  cannot load such file -- rexml/document
# ./config/application.rb:7:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/my_test_app_spec.rb:1:in `require'
# ./spec/my_test_app_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 0.56783 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

## Expected behaviour

The rspec tests should run.

## Can you provide an example app?

```
git clone https://github.com/pachun/MyTestApp
cd MyTestApp
bundle
bundle exec rspec
```

**Comment by pachun** [comment]
[I think this may be related](https://github.com/rails/rails/pull/40281).

**Comment by pachun** [comment]
[I just found this](https://github.com/rspec/rspec-rails/pull/2398).

Whoops.

Feel free to close this issue!

For posterity, the latest versions (I think) of ruby and rails which you can use with rspec (AFAIK) are:

ruby 2.7.2
rails 6.0.3.4

Using those versions along with the installations steps described in the readme work! 🎉

I had installed the latest version of ruby on my new machine (3.0.0).

Nobody ever talks about how buying a newer, faster machine can _cost_ you time.

**Comment by JonRowe** [comment]
You can run rspec-rails on Rails 6.1, you just need to use the currently unreleased branch.

Your error is because you need to install `rexml` thanks to `rails-controller-tests`, it was removed from the standard gemset in Ruby 3.0.0 and some gems may fail without it. RSpec does not require it.

**Comment by bradeaton** [comment]
I'm running into this same error after upgrading a project from 6.0 to 6.1. I have installed v5.0.2 from github. I also installed the rexml gem. But, I have the same error. Is there a specific branch or tag I need to install?

**Comment by pirj** [comment]
> I also installed the rexml gem

What do you mean by that, @bradeaton ? Have you added it to your Gemfile?

**Comment by bradeaton** [comment]
Yes. I added it to my Gemfile

**Comment by pirj** [comment]
What happens if you `require 'rexml/document'` from `rails console`? What is in the `$LOAD_PATH`?
If you set a breakpoint before the line (is it in `application.rb`, too?) when you run `rspec`, can you require it? What is in `$LOAD_PATH`? Is there a `Bundler.require(*Rails.groups)`? Can you share your `config/application.rb`?
What is the full backtrace (`rspec --backtrace`)?

**Comment by bradeaton** [comment]
Well, I just fixed it. Looking deeper into the stack trace I found it referencing an error in Rollbar. Updated to the latest Rollbar gem (3.3.0) and everything seems to be working fine now.

Thanks for the reply though @pirj

**Comment by jaredbeck** [comment]
This can also happen if something in your `spec_helper`/`rails_helper` raises a `SystemExit`.

I had this issue after updating from rails 6.0 to 6.1, because I forgot to run the pending migrations created by the [`app:update`](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-update-task) task. The pending migration check in my `rails_helper` called `exit`, which raises `SystemExit`, which I guess RSpec rescues?

It would be nice if RSpec printed "Hey, I encountered a `SystemExit`" instead of saying "No examples found" 🤷

**Comment by pirj** [comment]
@jaredbeck We track this in https://github.com/rspec/rspec-core/issues/2508

**Comment by ismailaidar** [comment]
Any updates?

**Comment by pirj** [comment]
@ismailaidar A PR is still welcome for https://github.com/rspec/rspec-core/issues/2508
