### ISSUE TITLE
Broken array request param.

### ISSUE THREAD

**Issue by abigoroth** [rspec/rspec-rails#2618]
## What Ruby, Rails and RSpec versions are you using?

ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
Rails 6.1.4.1
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.2
  - rspec-rails 5.0.1
  - rspec-support 3.10.2

## Observed behaviour
I have this in my rspec-request param 
`let(:'city_eq[]') { [alor_setar_id, shah_alam_id] }`

I am trying to get with this param. But it return broken param format.
```
 "city_eq"=>["150350,76561"]
```

## Expected behaviour
The param 
```
params[:city_eq] ["76410", "76561"]
```
with each of the id is encapsulated with the double quote.

## I have also tried
I have separated the param like what I did in Postman
```
          let(:'city_eq[]') { [shah_alam_id] }
          let(:'city_eq[]') { [alor_setar_id] }
```
This also is a no go.

**Comment by JonRowe** [comment]
:wave:  What is `rspec-request`? Is this a library your using? `let` just creates memoized local methods holding values, so you normally wouldn't even be able to use this without doing `send`... However params encoding such as `post 'my_path', params: {city_eq: ["150350","76561"]}` is handled by Rails directly and expects Ruby isms not URI params, so you may just be missing that...

I'm closing this for two reasons, I don't think this an rspec-rails issue and because we don't generally use issues for help requests, we prefer people use other resources such as IRC, Community Slacks, Help sites likes stack overflow or our mailing list.

**Comment by yakobre** [comment]
Thanks for pointing out those communication channel. I will head over there to seek help.

**Comment by abigoroth** [comment]
I am using this block structure 
```
path do -> get do -> context do -> response do -> let..
```
and the memoized local variable is declared inside the response block.

here is my code actually looks like.

```
      context 'filter jobs by city' do
        response '200 ', 'successfully return job(s) based on filter params' do
          let(:'access-token') { auth_headers['access-token'] }
          let(:client) { auth_headers['client'] }
          let(:'city_eq[]') { [alor_setar_id, shah_alam_id] }
```

I tried connect to irc.freenode.org but it is not connecting, 

What is the right way to have array parameter inside this response block ?
