### ISSUE TITLE
Disable Capybara for Rails API

### ISSUE THREAD

**Issue by chrishough** [rspec/rspec-rails#2662]
Has anyone been able to use the `features` or `system` folder without having to load Capybara i.e. remove Capybara from Rspec?

**Comment by JonRowe** [comment]
:wave: Folders automatically bring in example group types if you're using the `infer_spec_type_from_file_location!` option, so I assume you're talking about the example groups types here, I'm afraid the answer is "no" as the feature example group requires Capybara as its behaviour stems from that library, and the system test example group uses rails own built in system testing behaviour and similarly that requires capybara...

However request specs here should allow you to test the full api stack...

Closing because this isn't a bug report or feature request (we usually encourage people to use the mailing list, irc or other community channels for help requests, but I'm happy to answer any follow up questions here)

**Comment by chrishough** [comment]
That makes sense @JonRowe, thank you
