### ISSUE TITLE
Specifying :format => :json doesn't yield same result as setting request.accept

### ISSUE THREAD

**Issue by clupprich** [rspec/rspec-rails#710]
As far as I understood from the Rails source code, specifying the paramter :format should have the same result as setting the content type on the request. Now, I have the following setup (routes, controller and spec):

``` ruby
resource :user do
  resources :favorites, :only => [] do
    post 'toggle/:object_id', :action => 'toggle', :on => :collection, :as => 'toggle'
  end
end
```

``` ruby
def toggle
  object = Object.find_by_id(params[:object_id])
  respond_to do |format|
    format.json do
      render :json => { :is_favorite => is_favorite, :id => object.id }
    end
  end
end
```

``` ruby
request.accept = "application/json"
post :toggle, { :object_id => object.id }
```

This setup works great. However, I would also expect that this one works (note the format parameter), but it fails with either a 406 or RoutingError.

``` ruby
post :toggle, :object_id => object.id, :format => 'json' }
```

Does anybody know why? I would consider this to be a bug within the post method, or?

**Comment by snex** [comment]
I too am seeing this issue. ActionController::TestCase does not seem to be setting the CONTENT_TYPE header to "application/json" when "format: :json" is specified, but rather it defaults to "application/x-www-form-urlencoded"

Most of the time, this will not cause any problems and the parameters will be parsed correctly. However, I only found this issue because I am trying to pass empty arrays as parameters, and they are being eaten when ".to_query" or ".to_param" is called on my parameters.
