### ISSUE TITLE
RSpec with Rails 4.1.0.beta, warning: you should require 'minitest/autorun' instead

### ISSUE THREAD

**Issue by gwshaw** [rspec/rspec-rails#758]
In trying to run RSpec 2.14.0.rc1 on Rails 4.1.0.beta, I immediately get a warning: 

```
you should require 'minitest/autorun' instead
```

 that comes up in the backtrace assigned to the line

```
require 'rspec/rails'
```

 in `spec_helper.rb` If I add this before it

```
require 'minitest/autorun'
```

 the warning goes away. Alternatively, the problem goes away without changing the `spec_helper.rb` file if I add

```
gem 'minitest'
```

 to the gemfile

It will do this with a single spec file that only contains

```
require 'spec_helper'
```

**Comment by rudyrigot** [comment]
Note for people ending up on this thread as I did: I required 'minitest/autorun' as advised, which fixed the warning, but generated new errors, as it was now overriding Object to add a `stub` method, and I was already using the `stub` method that was already being imported by rspec.

After some fiddling, it turns out that I can require 'minitest/spec' instead, which will fix the warning, without messing with rspec's `Object#stub`.
