### ISSUE TITLE
Nested root route results in falsely passing specs

### ISSUE THREAD

**Issue by balexand** [rspec/rspec-rails#843]
To reproduce, create an empty Rails 4.0.0 project and add to your Gemfile:

``` ruby
group :development, :test do
  gem 'rspec-rails', '2.14.0'
end
```

Then run `bundle` and `rails generate rspec:install`.

Scaffold a test model/controller with `rails g scaffold post` and `bundle exec rake db:migrate RAILS_ENV=test`. The routes file (excluding comments) looks like:

``` ruby
Rspecmadness::Application.routes.draw do
  resources :posts
end
```

Running the generated controller spec  passes:

```
bundle exec rspec spec/controllers/posts_controller_spec.rb
```

Change the routes file to look like this:

``` ruby
Rspecmadness::Application.routes.draw do
  # resources :posts
end
```

and run the same controller spec. It now fails with errors saying "No route matches...". That's what we expect.

But then change the routes to look like:

``` ruby
Rspecmadness::Application.routes.draw do
  # resources :posts

  namespace :admin do
    root to: redirect("http://google.com/")
  end
end
```

Run the controller spec again. I'd expect to get a "No route matches..." error. But instead, the request is routed to `PostsController` as if the route existed.

In fact, in our app we noticed that after adding the nested root, all controller specs will route successfully, even if their corresponding routes are deleted.

**Comment by benjaminwood** [comment]
I know this is an old issue, but I came across this today and figured I could shed some light for other internet travelers.

I believe the core of the problem was first reported here: https://github.com/rails/rails/issues/6459

First attempt to address the problem was here: https://github.com/rails/journey/issues/47

And the actual fix was here: https://github.com/rails/rails/commit/aba0a17a61000ef43a51d7e9f63a0c209ba87cc6
