### ISSUE TITLE
undefined method `original_path_set' for nil:NilClass

### ISSUE THREAD

**Issue by chancancode** [rspec/rspec-rails#860]
Hi there! We are testing our apps against Rails master in anticipation of the soon-to-be-released Rails 4.1 to find problems early, and fix them before other people run into these issues.

When I'm running my tests, I see this warning:

```
An error occurred in an after hook
  NoMethodError: undefined method `original_path_set' for nil:NilClass
  occurred at /Users/godfrey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/rspec-rails-c566453e7f83/lib/rspec/rails/view_rendering.rb:121:in `block (2 levels) in <module:ViewRendering>'
```

Which is coming from here:

``` ruby
      included do
        before do
          unless render_views?
            @_empty_view_path_set_delegator = EmptyTemplatePathSetDecorator.new(controller.class.view_paths)
            controller.class.view_paths = ::ActionView::PathSet.new.push(@_empty_view_path_set_delegator)
            controller.extend(EmptyTemplates)
          end
        end

        after do
          unless render_views?
            controller.class.view_paths = @_empty_view_path_set_delegator.original_path_set
          end
        end
      end      
```

I tried setting a breakpoint in the before and after hook here, and for some reason, the `before` hook here is not being run, so when the `after` hook is ran, the instance variable is `nil`.

Here are the gem versions I'm using:

``` bash
% bundle list | grep rspec
  * rspec-collection_matchers (0.0.2)
  * rspec-core (3.0.0.beta1)
  * rspec-expectations (3.0.0.beta1)
  * rspec-mocks (3.0.0.beta1)
  * rspec-rails (3.0.0.beta1 c566453)
  * rspec-support (3.0.0.beta1)
```

Happy to provide more info to help hunt down the root cause!

**Comment by wtfiwtz** [comment]
For me, this was caused today by not being able to delete foreign key constraints on a PostgreSQL database. It seems that even as the owner of the PG table, this is not always an available privilege. One workaround is to force the test database user to be a super-user:

http://stackoverflow.com/questions/10757431/postgres-upgrade-a-user-to-be-a-superuser#answer-10757486

Perhaps there is another privilege that is more targeted but this solved the problem at least.

**Comment by afinetooth** [comment]
@wtfiwtz thanks for leaving your comment in this thread. It gave me the tip I needed to solve my own problem. 

For anyone else receiving the original exception:

    An error occurred in an after hook
        NoMethodError: undefined method `original_path_set' for nil:NilClass
        occurred at [...] in <module:ViewRendering>

What seems to be happening is that the *before hook* associated with the referred-to *after hook* in the exception, is failing to set a value for **@_empty_view_path_set_delegator**, which is the object later receiving **original_path_set** in the after hook. (See code below.)

The "why" of the issue can probably vary. 

@wtfiwtz reports that his PostgreSQL user didn't have permissions to delete cascading associations in his database, probably related to test cleanup by, I'm assuming, database_cleaner.

For me, it was a typo in a line of my database_cleaner config:

    config.before(:each) do
        DatabaseCleaner.strategy = :transaction
    end

(I was passing in the variable, *transaction*, instead of the symbol, *:transaction*.)

The point is that, this instructed DatabaseCleaner to use a strategy it didn't understand, blowing up *its* before hook, which failed up the chain to the before hook in RSpec's ViewRendering module: 

    included do
        before do
          unless render_views?
            @_empty_view_path_set_delegator = EmptyTemplatePathSetDecorator.new(controller.class.view_paths)
            controller.class.view_paths = ::ActionView::PathSet.new.push(@_empty_view_path_set_delegator)
            controller.extend(EmptyTemplates)
          end
        end

        after do
          unless render_views?
            controller.class.view_paths = @_empty_view_path_set_delegator.original_path_set
          end
        end
    end

Such that, in my case, the *before hook* above wasn't even running. Thus, it failed to set **@_empty_view_path_set_delegator**.

So, my advice, generalize the problem to this *before hook* failing and start looking for good reasons why. Configs in your test setup related to before blocks being excellent places to start!

**Comment by JonRowe** [comment]
Can you open a separate PR for that issue? our before hook should probably run regardless, or we should cope with the lack of the variable.
